name: Rust

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Update rust
        run: rustup update stable
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.100
      - name: Install wasm-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo xtask run-wasm --release --no-serve
      - name: Run tests
        run: cargo test --verbose
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: target/generated

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
