name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli
    - name: Install wasm-unknown-unknown target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo xtask run-wasm --release --no-serve
    - name: Run tests
      run: cargo test --verbose
